png("plot4.png")
par(mfcol=c(2,2))
plot(hhps$tstmp,hhps$Global_active_power,type="n",ylab="Global Active Power (kilowats)",xlab="")
lines(hhps$tstmp,hhps$Global_active_power)
plot(hhps$tstmp,hhps$Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
lines(hhps$tstmp,hhps$Sub_metering_1,col="black")
points(hhps$tstmp,hhps$Sub_metering_2,type="n")
lines(hhps$tstmp,hhps$Sub_metering_2,col="red")
points(hhps$tstmp,hhps$Sub_metering_3,type="n")
lines(hhps$tstmp,hhps$Sub_metering_3,col="blue")
legend("topright",lwd=2,col=c("black","red","blue"),legend=c("Sub metering 1","Sub metering 2","Sub metering 3"))
plot(hhps$tstmp,hhps$Voltage ,type="n",ylab="Voltage",xlab="datetime")
lines(hhps$tstmp,hhps$Voltage)
plot(hhps$tstmp,hhps$Global_reactive_power,type="n",ylab="Global ReActive Power",xlab="datetime")
lines(hhps$tstmp,hhps$Global_reactive_power)
dev.off()
