 png("plot3.png")
plot(hhps$tstmp,hhps$Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
lines(hhps$tstmp,hhps$Sub_metering_1,col="black")
points(hhps$tstmp,hhps$Sub_metering_2,type="n")
lines(hhps$tstmp,hhps$Sub_metering_2,col="red")
points(hhps$tstmp,hhps$Sub_metering_3,type="n")
lines(hhps$tstmp,hhps$Sub_metering_3,col="blue")
legend("topright",lwd=2,col=c("black","red","blue"),legend=c("Sub metering 1","Sub metering 2","Sub metering 3"))
 dev.off()